### PR TITLE
feat(metrics): optimize metrics

### PR DESCRIPTION
**Pull request by CoderPoet**
#### What type of PR is this?

feat(metrics): optimize metrics instrumentation

#### What this PR does / why we need it (English/Chinese):

en:
1. add request count metric: record the number of client and server requests
2. add route formatter: customize the value method of HTTP route to prevent high cardinality of metrics
3. add util for metrics unit test

zh:
1. 新增请求数指标：支持单独记录客户端、服务端请求数
2. 新增 route formmatter ：支持自定义 HTTP route 的取值方式，防止指标高基数问题
3. 新增指标单测的工具方法

### CODE REVIEW

**Comment by li-jin-gou** [comment]
ci need to fix

**Comment by GuangmingLuo** [comment]
新增的go文件加一下 license header

**Comment by CoderPoet** [comment]
> 新增的go文件加一下 license header

忘记了，补上了哈

**Comment by CoderPoet** [comment]
> ci need to fix

done

**Review by rogerogers — APPROVED** [review]

**Pull request merged**
