### PR TITLE
feat: Add trace ID to the response header.

### PR DESCRIPTION
**Pull request by lafer-fz**
#### What type of PR is this?
feat: Add trace ID to the response header.

#### What this PR does / why we need it (English/Chinese):
During the debugging process, it may be necessary to use the trace ID to troubleshoot issues. As a server-side developer, I would appreciate it if others could provide me with the trace ID of the problematic requests.

#### Which issue(s) this PR fixes:
Fixes(https://github.com/hertz-contrib/obs-opentelemetry/issues/23)

### CODE REVIEW

**Comment by rogerogers** [comment]
Maybe we should add a switch and an option for the header key configure.

**Comment by lafer-fz** [comment]
Yes, I think what you said is very accurate. I have made the changes, please review again.

**Comment by rogerogers** [comment]
The configuration of HTTP header names may be very useful, as some one may want to use x-trace-id, x-request-id, and so on.

**Comment by lafer-fz** [comment]
Absolutely, configuring the HTTP header names would indeed be valuable, as different individuals might prefer using various names like x-trace-id, x-request-id, and so on. While HTTP header names should be configurable, I'd like to suggest having a default value: x-b3-traceid. The reason behind choosing x-b3-traceid as the default is because the Heartz library employs the B3 implementation of propagation.TextMapPropagator by default, which utilizes x-b3-traceid as the HTTP header name for trace IDs.
image
image

**Comment by rogerogers** [comment]
I think the default trace-id is sufficient. "b3" is a header used for zipkin distributed tracing. When used in the response header, it can be a bit confusing.

**Comment by lafer-fz** [comment]
Okay, use trace-id by default.

**Comment by CoderPoet** [comment]
@lafer-fz Thank you very much for your contribution, this is a very useful feature. 

However, the usual practice in the community is to abstract a mechanism for custom response headers, which is indeed more generic.

Consider referring to the Javaagent version implementation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/bootstrap/http/HttpServerResponseCustomizer.java

The traceid response header can be considered as a way to become a plugin integrated by default

/cc @rogerogers

**Comment by rogerogers** [comment]
I've been quite busy lately, i'll take a look at the Java implementation later. Additionally, Java itself is a bit more flexible.

**Comment by li-jin-gou** [comment]
PATL @rogerogers  @CoderPoet

**Review by li-jin-gou — APPROVED** [review]

**Review by CoderPoet — APPROVED** [review]
/LGTM

**Pull request merged**
