### PR TITLE
chore: bump otel version

### PR DESCRIPTION
**Pull request by rogerogers**
#### What type of PR is this?

chore

#### What this PR does / why we need it (English/Chinese):
bump deps version

### CODE REVIEW

**Review by li-jin-gou — APPROVED** [review]

**Comment by li-jin-gou** [comment]
PATl @CoderPoet

**Review by CoderPoet — APPROVED** [review]
/LGTM

**Comment by wanghao0123** [comment]
@rogerogers hi, any schedule about release a new version about this PR? I had met some import issue about version. thx

**Comment by rogerogers** [comment]
> @rogerogers hi, any schedule about release a new version about this PR? I had met some import issue about version. thx

Sorry, I forgot. Done.

**Pull request merged**
